{
    'author': "Immomakers",
    'website': "https://www.ViaSofie.be",
    'name': 'ViaSoTheme',
    'summary': 'Standaard thema voor de website',
    'description': 'Mooi',
    'category': 'Theme',
    'version': '1.1',
    'depends': ['website','sale'],
    'data': ['views/bootswatch-native.xml',
             'views/footer.xml',
             'views/welkom.xml',
             'views/referenties.xml',
             'views/advies.xml',
             'views/woningen.xml',
             'views/contact.xml',
             'views/woningview.xml',
             'views/search.xml'
            ],
    'application': False,
}
